### ISSUE TITLE
dist/FileAPI.flash.swf?r=2.0.21 not found

### ISSUE THREAD

**Issue by itsnotvalid** [jellyjs/angular2-file-drop#18]
After reviewing the code, it's found that it did not disable (or expose) the the option to disable usage of flash plugin or expose params to tune the location of the swf.

**Comment by NITIN-CODITAS** [comment]
Even i am getting the same issue. 
![screenshot from 2017-02-27 16 15 56](https://cloud.githubusercontent.com/assets/13882269/23358479/208e34b6-fd08-11e6-972f-e56255bf7f8c.png)

**Comment by ox4** [comment]
overriding fileapi entry point fixed the issue for me. 

for angular-cli projects in tsconfig.json add "path" property with the following value:
`"paths": {
      "fileapi": ["../node_modules/fileapi/dist/FileAPI.html5.min.js"]
    }`

for webpack projects add "resolve" to the webpack.config.json:
`resolve: {
    alias: {
      'fileapi': 'dist/FileAPI.html5.min.js'
    }
  }`

for system.js add the following property to "packages":
`'fileapi': { main: 'dist/FileAPI.html5.min.js', defaultExtension: 'js' },`
